FROM node:20

WORKDIR /app

# Copy package files
COPY package*.json ./

# Clean install
RUN npm ci --include=optional

# Copy source code
COPY . .

# Expose port
EXPOSE 5173

# Start the application
CMD ["npm", "run", "dev", "--", "--host"]